### PR TITLE
Fix the search bar and added the function

### LINKED ISSUE #15: Fixing the searchbar
*Bug in the searchbar
*add a function that updates the state inside the input onChange.

### PR DESCRIPTION
**Pull request by Gson44**
closes #15

### CODE REVIEW

File: client/src/Components/Search.js [hunk 1]
```diff
@@ -4,27 +4,38 @@ import axios from 'axios'
 import styles from './Search.module.css'
 
 class Search extends React.Component {
-  state = {
```
Comment (aaronholla) [inline client/src/Components/Search.js]: You can leave this as a class property its the same.

File: client/src/Components/Search.js [hunk 2]
```diff
@@ -4,27 +4,38 @@ import axios from 'axios'
...
-    searchInput: ""
+  constructor(props) {
+    super(props);
+    this.state = {
+      inputValue: ''
+    };
   }
 
   searchResult = () => {
     axios(`/products/search/${this.state.searchInput}`)
```
Comment (aaronholla) [inline client/src/Components/Search.js]: `this.state.searchInput` should be `this.state.inputValue` instead.

File: client/src/Components/Search.js [hunk 3]
```diff
@@ -4,27 +4,38 @@ import axios from 'axios'
...
-  state = {
-    searchInput: ""
+  constructor(props) {
+    super(props);
+    this.state = {
+      inputValue: ''
+    };
   }
 
   searchResult = () => {
```
Comment (aaronholla) [inline client/src/Components/Search.js]: also can you add an event.preventDefault here so the page wont reload on submit.
